name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Ubuntu 24.04"
            runner: ubuntu-24.04
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Boost (headers & libs)
        id: install-boost
        uses: MarkusJx/install-boost@v2.4.4
        with:
          boost_version: 1.86.0

      - name: Expose Boost to CMake
        run: |
          echo "BOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}" >> $GITHUB_ENV
          echo "Boost_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}" >> $GITHUB_ENV

      - name: Install Python deps (PyTorch CPU + pybind11)
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install pybind11

      - name: Export pybind11_DIR
        run: echo "pybind11_DIR=$(python - <<'PY'
          import pybind11, pathlib
          print(pybind11.get_cmake_dir())
          PY
          )" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DMAKE_PYTAMI=ON

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

      - name: Test
        run: ctest --test-dir build -C ${{ env.BUILD_TYPE }} --output-on-failure
